#!/usr/bin/env bash

set -e

PROJECT_NAME="python_starter"
PYTHON_VERSION="3.14.0"

# Use project root as working directory
cd "$(dirname -- "$0";)/.." || exit 1

if ! pyenv --version; then
  echo "Install pyenv"
  exit 1
fi

if ! pyenv virtualenv --version; then
  echo "Install pyenv-virtualenv"
  exit 1
fi

pyenv install --skip-existing $PYTHON_VERSION
pyenv local $PYTHON_VERSION
pyenv uninstall -f $PROJECT_NAME
pyenv virtualenv $PYTHON_VERSION $PROJECT_NAME -f
pyenv local $PROJECT_NAME

pip install --upgrade pip
pip install wheel
pip install -r requirements.txt

pyenv rehash

pre-commit install
pre-commit run &> /dev/null # Run once to initialize environments
